### PR TITLE
Updated getComment function and GET request

### PR DESCRIPTION
**Pull request by dcheng1290**
I just updated the getComment function and GET request so that it can actually grab with ID.

### CODE REVIEW

**Review by HourglassMagi — CHANGES_REQUESTED** [review]
Hey David, this looks pretty good, I only had one question before I approved this PR. In your express get handler, I don't see a case for if the record was not found that would send an error back to the client letting them know that that recipe id was not in your database.   If that's the case I think it would be good to send a 404 error letting the client know the resource wasn't found.

**Comment by HourglassMagi** [comment]
[PR David's server(GET request updated) and getComment function in database(updated)](https://trello.com/c/BSo8oCVZ/37-pr-davids-serverget-request-updated-and-getcomment-function-in-databaseupdated)

**Comment by dcheng1290** [comment]
Hey Laurent, thanks for reviewing my code. I think I was only trying to update the code so it did not show the full file but I included a status 400 code in case of an error. I updated it to 404 instead in my newest commit!

**Review by HourglassMagi — DISMISSED** [review]

**Comment by HourglassMagi** [comment]
Looks good! great job.

**Comment by dcheng1290** [comment]
Thanks Laurent. It made me try to resolve a conflict and it seems like it is asking for your approval again.

**Review by HourglassMagi — APPROVED** [review]
No problem. Thanks for fixing the merge conflicts.

**Pull request merged**
