### PR TITLE
About Blue Apron component

### PR DESCRIPTION
**Pull request by dcheng1290**
I created the "About blue Apron" component and added it onto my app.jsx file to render. Please ignore the CSS and HTML file!

### CODE REVIEW

**Comment by dcheng1290** [comment]
[PR David's new front end component for About Blue Apron](https://trello.com/c/JRKm1aPD/42-pr-davids-new-front-end-component-for-about-blue-apron)

**Comment by dcheng1290** [comment]
[PR David's new front end component for About Blue Apron](https://trello.com/c/JRKm1aPD/42-pr-davids-new-front-end-component-for-about-blue-apron)

**Review by jaweesner — COMMENTED** [review]
Looks good, but I would suggest changing some of the class names to more similar to the actual class function/styling---or use bootstrap so that they have meaning

**Review by jaweesner — APPROVED** [review]
no  need to look at this again, minor fixes don't need re-review

**Comment by dcheng1290** [comment]
Thanks for reviewing and I will update the class names to more similar to the actual class functions.

**Pull request merged**
